### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by orginux** [orginux/sql-cd#10]
Requirements:

- contents list of clusters
- each cluster contains a list of sources
- some options can be obtained from environment variables
- YAML format
- read the config from a git repository

```yaml
---
clusters:
  - cluster-1:
      host: hostname.my
      port: 8443
      user: user | ENV
      pass: **** | ENV
      source:
        - git-repo: http://....
          git-path: queries/common
          git-uesr: user
          git-pass: **** | ENV
        - git-repo: http://....
          git-path: queries/cluster/team
        - git-repo: http://....
          git-path: queries/cluster/system
          git-ssh-key: ***** | ENV

```
